import { GetServerSideProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import {sanityClient, UrlFor } from '../sanity'
import { Collection } from '../typings'

interface Props{
  collections: Collection[],
}

export default function Home({ collections }: Props) {
  return (
    <div className='max-w-[65rem] mx-auto flex flex-col min-h-screen py-12 px-10 2xl:px-0'>
      <Head>
        <title>NFT Drop || Web 3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="mb-10 text-4xl font-extralight">The <span className="font-extrabold underline decoration-pink-600/50">Addips</span> NFT Market Place</h1>
      
      <main className='bg-slate-100 p-10 shadow-xl shadow-rose-400/20 rounded-md'>
        <div className='grid space-x-3 md:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4'>
          {collections.map(collection => (
            <><Link href={`/nft/${collection.slug.current}`}>
              
              <div className='flex flex-col items-center cursor-pointer transition-all duration-150 hover:scale-105'>
              <img className='h-96 w-60 rounded-2xl object-cover' src={UrlFor(collection.mainImage).url()} alt="" />

              <div className='p-5'>
                <h2 className='text-3xl'>{collection.title}</h2>
                <p className='mt-2 text-sm text-gray-400'>{collection.description}</p>
              </div>
            </div>
            </Link>   
          </>
          ))}
        </div>
      </main>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  const query = `*[_type == "collection"]{
    _id,
    title,
    address,
    description,
    nftCollectionName,
    "mainImage": mainImage.asset->url,
    "previewImage": previewImage.asset->url,
    slug {current},
    "creator": creator->{
      _id,
      name,
      address,
      slug {current},
    }
  }  
  `
  const collections = await sanityClient.fetch(query)
  return {
    props: {
      collections
    }
  }
}
